<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Package">
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <PackageReleaseNotes>Net 8 support</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Indice.Cryptography" Version="$(VersionPrefix)" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
    <PackageReference Include="AutoMapper" Version="16.1.1">
      <NoWarn>NU1608</NoWarn>
    </PackageReference>
    <PackageReference Include="Indice.IdentityServer4" Version="4.1.9" />
    <PackageReference Include="Indice.IdentityServer4.EntityFramework.Storage" Version="4.1.9" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net9.0' ">    
    <PackageReference Include="Duende.IdentityServer" Version="7.2.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Indice.Cryptography\Indice.Cryptography.csproj" />
  </ItemGroup>
</Project>
